name: XDN CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java (Temurin 21)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Ant
        run: |
          sudo apt-get update
          sudo apt-get install -y ant

      - name: Build JARs
        run: |
          ant jar

      - name: Archive built jars
        uses: actions/upload-artifact@v4
        with:
          name: xdn-jars
          path: jars

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download built jars
        uses: actions/download-artifact@v4
        with:
          name: xdn-jars

      - name: Set up Java (Temurin 21)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Ant
        run: |
          sudo apt-get update
          sudo apt-get install -y ant

      - name: Run default integration test
        run: |
          ant test

      - name: Run a specific target
        run: |
           ant runtest -Dtest=edu/umass/cs/reconfiguration/testing/TESTReconfigurationMain
#          ant runtest -Dtest=edu/umass/cs/gigapaxos/testing/TESTPaxosMain

      - name: Run unit test from tests directory
        run: |
          ant xdn-unit-tests